#!/bin/bash

## Copyright (C) 2019 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

if [ -f /usr/libexec/helper-scripts/pre.bsh ]; then
   source /usr/libexec/helper-scripts/pre.bsh
fi

## https://github.com/QubesOS/build-issues/issues/1769
export DPKG_MAINTSCRIPT_PACKAGE="whonix-ws-network-conf"
export DPKG_MAINTSCRIPT_NAME="postinst"

/bin/bash -x /var/lib/dpkg/info/whonix-ws-network-conf.postinst configure
