#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

if [ -f /usr/libexec/helper-scripts/pre.bsh ]; then
   source /usr/libexec/helper-scripts/pre.bsh
fi

## https://github.com/QubesOS/build-issues/issues/1769
mv /etc/resolv.conf /etc/resolv.conf.whonix-orig
mv /etc/resolv.conf.tb-updater-bak /etc/resolv.conf
