#!/bin/bash

## Copyright (C) 2019 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

#update-torbrowser --input gui

/usr/libexec/helper-scripts/terminal-wrapper update-torbrowser
