#!/bin/bash

## Copyright (C) 2019 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

if [ -e /run/qubes/this-is-templatevm ]; then
   pkexec DISPLAY="$DISPLAY" update-torbrowser --input gui
else
   update-torbrowser --input gui
fi
