.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "UPDATE\-I2PBROWSER" "1" "April 2020" "tb-updater" "tb-updater Manual"
.SH "NAME"
\fBupdate\-i2pbrowser\fR \- i2p Browser Updater by Whonix developers
.P
.SH "SYNOPSIS"
\fBupdate\-i2pbrowser\fR [option(s)]
.SH "DESCRIPTION"
Lets you safely download the Tor Browser Bundle (TBB) from The Tor Project\'s (TPO) website, then it modifies it for use with the i2p network\. It enforces TLS encryption (https) for TPO\'s website, downloads TBB from the TPO\'s website, and uses OpenPGP verification\.
.P
In case there is already a \fB~/\.i2pb\fR folder, it renames it to ~/\.i2pb_(current date and time)\. It extracts freshly downloaded TBB too to \fB~/\.i2pb/i2p\-browser_(current date and time)\fR\.
.P
Default action when no options are given is to performs an update check and ask how you want to proceed\.
.SH "OPTIONS"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "AVAILABLE LANGUAGES"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "MORE LANGUAGES"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "CONFIG FILE"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "EXIT CODES"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "EXAMPLES"
\fBupdate\-i2pbrowser\fR
.P
\fBupdate\-i2pbrowser \-\-update \-\-lang="vi"\fR
.P
\fBtimeout 600 update\-i2pbrowser \-\-ordinary\fR
.SH "BUGS"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "NOTES"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "PORTING"
Same as \fBupdate\-torbrowser\fR\. See: man update\-torbrowser
.SH "WWW"
https://www\.whonix\.org/wiki/Tor_Browser
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
