#!/bin/bash

set -e

mydir="$( cd "$( dirname "$0" )" && pwd )"
cd "$mydir"
cd ..
cd ..
cd ..

source ./usr/lib/tbbversion_parser

for RecommendedTBBVersions in ./usr/share/tb-updater/unit-test/RecommendedTBBVersions ./usr/share/tb-updater/unit-test/RecommendedTBBVersions2 ; do
   test -f "$RecommendedTBBVersions"

   tbbversion

   echo "tbb_recommended_versions_list: $tbb_recommended_versions_list"

   for tbb_version in $tbb_recommended_versions_list; do
      echo "tbb_version: $tbb_version"
   done
   echo "----------"
done

echo "OK"
