#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

if [ -e /run/qubes/this-is-templatevm ]; then
   lxsudo update-torbrowser --input gui
else
   update-torbrowser --input gui
fi
