#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e
set -x

cache_folder="/var/cache/tb-updater"
done_file="$cache_folder/first-boot-home-population.done"

if [ -e "$done_file" ]; then
   exit 0
fi

if command -v qubesdb-read >/dev/null 2>&1 ; then
   qubes_vm_type="$(qubesdb-read /qubes-vm-type)"
   qubes_vm_name="$(qubesdb-read /name)"
fi

## Avoid running in Qubes DVM Template.
## https://phabricator.whonix.org/T726
if echo "$qubes_vm_name" | grep -q "\-dvm" ; then
   exit 0
fi

if [ "$qubes_vm_type" = "TemplateVM" ]; then
   exit 0
fi

user_name="user"
home_dir="/home/$user_name"

if [ ! -d "$home_dir" ]; then
   exit 0
fi

if [ -d /var/cache/tb-binary ]; then
   chown --recursive "$user_name:$user_name" /var/cache/tb-binary
fi

shopt -s dotglob
shopt -s nullglob

for folder_name in /var/cache/tb-binary/*; do
   sudo --non-interactive -u "$user_name" cp --verbose --recursive --no-clobber "$folder_name" "$home_dir"
done

mkdir -p "$cache_folder"
touch "$done_file"
