#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e
set -x

cache_folder="/var/cache/tb-updater"
done_file="$cache_folder/first-boot-home-population.done"

if [ -e "$done_file" ]; then
   exit 0
fi

if command -v qubesdb-read >/dev/null 2>&1 ; then
   qubes_vm_type="$(qubesdb-read /qubes-vm-type)"
fi

if [ "$qubes_vm_type" = "TemplateVM" ]; then
   exit 0
fi

user_name="user"
home_dir="/home/$user_name"

if [ ! -d "$home_dir" ]; then
   exit 0
fi

shopt -s dotglob
shopt -s nullglob

for folder_name in /var/cache/tb-binary/*; do
   sudo -u "$user_name" cp --verbose --recursive --no-clobber "$folder_name" "$home_dir"
done

mkdir -p "$cache_folder"
touch "$done_file"
